settings:
  save_root: D:\temp
  data_dirname_prefix: data
  file_info_dirname: fileinfo
  issues_save_dirname: issues
  pulls_save_dirname: pulls
  issues_list_filename: issues_info.csv
  pulls_list_filename: pulls_info.csv
  errors_list_filename: errors_info.csv
  download_settings:
    -
      type: github
      api_root: https://api.github.com
      token: input_token_here
      org: tensorflow
      identifier_prefix:
      identifier_postfix:
      sleepSecond: 30
      repository_names:
        - tensor2tensor
        - models
      issues_settings:
        -
          filter: all
          state: open
          labels: 
          sort: created
          direction: asc
          since: 
      pulls_settings:
        -
          state: all
          head:
          base:
          sort:
          direction:
    -
      type: github
      api_root: https://api.github.com
      token: input_token_here
      org: terasolunaorg
      identifier_prefix:
      identifier_postfix:
      sleepSecond: 30
      repository_names:
        - tutorial-apps
      issues_settings:
        -
          filter: all
          state: all
          labels: 
          sort: created
          direction: asc
          since: 
      pulls_settings:
        -
          state: all
          head:
          base:
          sort:
          direction:
proxy:
  use_proxy: false
  server: com.example
  port: 8080
  user_id: userid
  password: passwd
