# issues
#   filter: assined, created, mentioned, subscribed, all
#   state: open, closed, all
#   labels: A list of comma separated label names. Example: bug,ui,@high
#   sort: created, updated, comments
#   direction: asc, desc
#   since: Only issues updated at or after this time are returned. This is a timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.

settings:
  issues_list_file_path: D:\temp\fileinfo\issues_info.csv
  pulls_list_file_path: D:\temp\fileinfo\pulls_info.csv
  errors_list_file_path: D:\temp\fileinfo\errors_info.csv
  issues_save_dir: D:\temp\issues
  pulls_save_dir: D:\temp\pulls
  issues:
    -
      type: github
      api_root: https://api.github.com
      token: input_token_here
      org: tensorflow
      filter: all
      state: all
      labels: 
      sort: created
      direction: asc
      since: 
      sleepSecond: 30
      identifier_prefix:
      identifier_postfix:
      repository_names:
        -
        -
    -
      type: github
      api_root: https://api.github.com
      token: input_token_here
      org: terasolunaorg
      filter: all
      state: all
      labels: 
      sort: created
      direction: asc
      since: 
      sleepSecond: 30
      identifier_prefix: GitBucket_
      identifier_postfix:
      repository_names:
        -
        -
proxy:
  use_proxy: false
  server: com.example
  port: 8080
  user_id: userid
  password: passwd
